name: Locust Performance Test

on: [push]

jobs:
  locust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Dependencies
      run: |
        pip install locust
        
    - name: Run Locust
      run: |
        HOST=$(jq -r .host config.json)
        USERS=$(jq .users config.json)
        SPAWN_RATE=$(jq .spawn_rate config.json)
        RUN_TIME=$(jq -r .run_time config.json)
        locust -f locust.py --headless \
        -u $USERS -r $SPAWN_RATE \
        --run-time $RUN_TIME \
        --host $HOST \
        --csv=locust_results
        
    - uses: actions/upload-artifact@v2
      with:
        name: locust-results
        path: locust_results_*.csv
