name: Locust Performance Test

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Target host for the load test'
        required: true
      users:
        description: 'Number of concurrent users'
        required: true
      spawn_rate:
        description: 'Rate at which users are spawned'
        required: true
      run_time:
        description: 'Duration of the load test'
        required: true

jobs:
  locust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Dependencies
      run: |
        pip install locust
        
    - name: Run Locust
      env:
        HOST: ${{ inputs.host }}
        USERS: ${{ inputs.users }}
        SPAWN_RATE: ${{ inputs.spawn_rate }}
        RUN_TIME: ${{ inputs.run_time }}
      run: |
        locust -f locust.py --headless \
        -u $USERS -r $SPAWN_RATE \
        --run-time $RUN_TIME \
        --host $HOST \
        --csv=locust_results
        
    - uses: actions/upload-artifact@v2
      with:
        name: locust-results
        path: locust_results_*.csv
